services:
  server:
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - app_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  mongodb_data:
