# Use the official .NET SDK image as the build environment
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy the .csproj and restore as distinct layers
COPY . .
RUN dotnet restore

# Copy everything else (including tests)
COPY . .

# Run the tests
CMD ["dotnet", "test"]
