version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my_network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

volumes:
  mongodb_data:

networks:
  my_network:
