version: '3.9'

services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - blog_app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # PostgreSQL service
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_app_network

networks:
  blog_app_network:


volumes:
  postgres_data:
  mongo_data:
